
name: PR workflow

on:
  pull_request_target:
    types: [opened, reopened, edited]
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Case of Failure
        id: print
        run: echo '1. ${{ github.base_ref }}, 2. ${{ github.event.pull_request.base.ref }}'